version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: FakeNewsFilter.API/Dockerfile
    ports:
      - "2000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
        - sqlserver

  adminapp:
    build:
      context: .
      dockerfile: FakeNewsFilter.AdminApp/Dockerfile
    ports:
      - "2001:80"

  userapp:
    build:
      context: .
      dockerfile: FakeNewsFilter.UserApp/Dockerfile
    ports:
      - "2002:80"

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "MyPass@word"
      ACCEPT_EULA: "Y"
      MSSQL_USER: "sa"
