// <auto-generated />
using System;
using FakeNewsFilter.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FakeNewsFilter.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");

                    b.HasData(
                        new
                        {
                            Key = "Home Title",
                            Value = "This is homepage"
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Follow", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TopicId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.ForgotPassword", b =>
                {
                    b.Property<int>("IdForgotPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdForgotPassword");

                    b.ToTable("ForgotPassword");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "vi",
                            Flag = "vi.png",
                            IsDefault = true,
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            Id = "en",
                            Flag = "en.png",
                            IsDefault = false,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("PathMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(959),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "covid.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 2,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1221),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "taliban.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 3,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1233),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "kinh-te-tg.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 4,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1235),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "ngvietnamchau.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 5,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1236),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "doanh-nghiep.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 6,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1237),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "chon truong.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 7,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1238),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "congnghegame.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 8,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1240),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "congnghemoi.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 9,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1313),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "phongsu.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 10,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1314),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "giaothong.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 11,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1316),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "chungkhoan.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 12,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1317),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "khoahocvn.jpeg",
                            SortOrder = 0,
                            Type = 1
                        },
                        new
                        {
                            MediaId = 13,
                            DateCreated = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(1318),
                            Duration = 0,
                            FileSize = 0L,
                            PathMedia = "the-thao1.jpeg",
                            SortOrder = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ThumbNews")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("NewsId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ThumbNews")
                        .IsUnique()
                        .HasFilter("[ThumbNews] IS NOT NULL");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = 1,
                            Content = "Test",
                            DatePublished = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taliban fighters poured into the Afghan capital on Sunday amid scenes of panic and chaos, bringing a swift and shocking close to the Afghan government and the 20-year American era in the country.",
                            LanguageId = "en",
                            Name = "Kabul’s Sudden Fall to Taliban Ends U.S. Era in Afghanistan",
                            Publisher = "New York Times",
                            Source = "test",
                            Status = 0,
                            ThumbNews = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(7256)
                        },
                        new
                        {
                            NewsId = 2,
                            Content = "Test",
                            DatePublished = new DateTime(2021, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The masking orders in Dallas and Bexar counties were issued after a lower court ruled last week in favor of local officials.",
                            LanguageId = "en",
                            Name = "Texas high court blocks mask mandates in two of state's largest counties",
                            Publisher = "NBC News",
                            Source = "test",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9234)
                        },
                        new
                        {
                            NewsId = 3,
                            Content = "Test",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A lagging vaccination campaign and the spread of the highly contagious Delta variant are driving a surge in Covid-19 hospitalizations in the United States..",
                            LanguageId = "en",
                            Name = "Hospitalizations of Americans under 50 have reached new pandemic highs",
                            Source = "test",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9251)
                        },
                        new
                        {
                            NewsId = 4,
                            Content = "Test",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A lagging vaccination campaign and the spread of the highly contagious Delta variant are driving a surge in Covid-19 hospitalizations in the United States..",
                            LanguageId = "en",
                            Name = "Hospitalizations of Americans under 50 have reached new pandemic highs",
                            Source = "test",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9253)
                        },
                        new
                        {
                            NewsId = 5,
                            Content = "Ngoại giao",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hai cửa khẩu biên giới giữa Myanmar với Trung Quốc mở cửa lại từ ngày 26.11 với hy vọng hướng đến việc phục hồi thương mại bình thường giữa 2 nước..",
                            LanguageId = "vi",
                            Name = "Myanmar-Trung Quốc mở lại 2 cửa khẩu biên giới sau 7 tháng đóng cửa chống Covid-19",
                            Source = "https://thanhnien.vn/myanmar-trung-quoc-mo-lai-2-cua-khau-bien-gioi-sau-7-thang-dong-cua-chong-covid-19-post1405895.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9255)
                        },
                        new
                        {
                            NewsId = 6,
                            Content = "Ngoại giao",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giới phân tích cảnh báo rằng việc mất tín hiệu của nhiều tàu thuyền ở Trung Quốc gây xáo trộn chuỗi cung ứng.",
                            LanguageId = "vi",
                            Name = "Vì sao nhiều tàu thuyền ‘biến mất’ ở vùng biển Trung Quốc?",
                            Source = "https://thanhnien.vn/vi-sao-nhieu-tau-thuyen-bien-mat-o-vung-bien-trung-quoc-post1405317.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9258)
                        },
                        new
                        {
                            NewsId = 7,
                            Content = "Ngoại giao",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quan hệ kinh tế Mỹ và Đài Loan vừa có thêm bước tiến mới, hàm chứa các hợp tác có vai trò quan trọng trong việc đối phó với sự trỗi dậy của Trung Quốc.",
                            LanguageId = "vi",
                            Name = "Bước ngoặt liên minh kinh tế Mỹ - Đài Loan",
                            Source = "https://thanhnien.vn/buoc-ngoat-lien-minh-kinh-te-my-dai-loan-post1404652.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9260)
                        },
                        new
                        {
                            NewsId = 8,
                            Content = "Du lịch",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lượng khách quốc tế đến Thái Lan đã tăng mạnh sau khi nước này nới lỏng quy định cách ly cho người đã tiêm vắc xin Covid-19.",
                            LanguageId = "vi",
                            Name = "Lượng khách quốc tế đến Thái Lan tăng mạnh sau mở cửa",
                            Source = "https://thanhnien.vn/luong-khach-quoc-te-den-thai-lan-tang-manh-sau-mo-cua-post1405440.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9262)
                        },
                        new
                        {
                            NewsId = 9,
                            Content = "Kinh tế",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các bộ trưởng APEC khẳng định sẽ tăng cường phối hợp và đẩy mạnh nghị trình hoạt động nhằm đảm bảo khôi phục tự do và an toàn đi lại tại khu vực.",
                            LanguageId = "vi",
                            Name = "Hướng đi phục hồi bền vững cho APEC",
                            Source = "https://thanhnien.vn/huong-di-phuc-hoi-ben-vung-cho-apec-post1400053.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9264)
                        },
                        new
                        {
                            NewsId = 10,
                            Content = "Dân tộc",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Để “săn” ốc đá và cá chình, 2 sản vật ngon bậc nhất ở núi rừng Quảng Trị.",
                            LanguageId = "vi",
                            Name = "Săn 'lộc trời': Lội suối nhặt ốc, vào thủ phủ cá chình",
                            Source = "https://thanhnien.vn/san-loc-troi-loi-suoi-nhat-oc-vao-thu-phu-ca-chinh-post1406363.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9265)
                        },
                        new
                        {
                            NewsId = 11,
                            Content = "Dân tộc",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuôn Ngọ là làng duy nhất cung cấp nguyên liệu các loại vỏ trai, ốc cho cả nước để làm đồ cẩn, khảm, thủ công mỹ nghệ.",
                            LanguageId = "vi",
                            Name = "Nghề Việt - Nét Việt: Nghề trai Chuôn Ngọ",
                            Source = "https://thanhnien.vn/nghe-viet-net-viet-nghe-trai-chuon-ngo-post1404658.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9267)
                        },
                        new
                        {
                            NewsId = 12,
                            Content = "Nông nghiệp",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khi mọi người bắt đầu lên giường đi ngủ, thì một ngày làm việc của công nhân cạo mủ cao su bắt đầu.",
                            LanguageId = "vi",
                            Name = "Nỗi lòng người cạo mủ cao su",
                            Source = "https://thanhnien.vn/noi-long-nguoi-cao-mu-cao-su-post1404643.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9269)
                        },
                        new
                        {
                            NewsId = 13,
                            Content = "Cảnh đẹp",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thác Drai Dlông với dòng chảy mạnh mẽ quanh năm giữa núi rừng là điểm đến không thể bỏ qua của những ai muốn khám phá Tây Nguyên.",
                            LanguageId = "vi",
                            Name = "Khám phá thác ba nhánh hùng vĩ ít người biết giữa Tây Nguyên",
                            Source = "https://thanhnien.vn/kham-pha-thac-ba-nhanh-hung-vi-it-nguoi-biet-giua-tay-nguyen-post1405776.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9270)
                        },
                        new
                        {
                            NewsId = 14,
                            Content = "Món ăn",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xôi là món ăn được rất nhiều người ưa thích vì dễ ăn và cách làm khá đơn giản, thế nhưng tại gia đình bà Nông Thị Mai.",
                            LanguageId = "vi",
                            Name = "Chiếc nồi cổ ‘thần kỳ’ tạo ra món xôi độc đáo của người Nùng ở Đắk Lắk",
                            Source = "https://thanhnien.vn/chiec-noi-co-than-ky-tao-ra-mon-xoi-doc-dao-cua-nguoi-nung-o-dak-lak-post1403687.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9272)
                        },
                        new
                        {
                            NewsId = 15,
                            Content = "Người Việt xa xứ",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Câu chuyện của hai anh em sống tại TP.Liverpool được kể lại trong loạt phim tài liệu Nail Bar Boys do Đài BBC khởi chiếu tuần qua.",
                            LanguageId = "vi",
                            Name = "Những đứa con tìm về nguồn cội",
                            Source = "https://thanhnien.vn/nhung-dua-con-tim-ve-nguon-coi-post1405816.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9274)
                        },
                        new
                        {
                            NewsId = 16,
                            Content = "Người Việt xa xứ",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Để tổ chức thành công triển lãm cá nhân đầu tiên tại Mỹ, họa sĩ tranh in Mai Trần đã trải qua một quá trình dài với nhiều gian nan, thử thách.",
                            LanguageId = "vi",
                            Name = "Mang chất Việt vào tranh in trên đất Mỹ",
                            Source = "https://thanhnien.vn/mang-chat-viet-vao-tranh-in-tren-dat-my-post1403198.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9276)
                        },
                        new
                        {
                            NewsId = 17,
                            Content = "Người Việt xa xứ",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Một nữ tiến sĩ người Việt được vinh danh là chuyên gia vật liệu hàng đầu tại Úc nhờ góp phần ứng phó cháy rừng tại nước này.",
                            LanguageId = "vi",
                            Name = "Người phụ nữ Việt phát triển vật liệu phủ chống cháy ở Úc",
                            Source = "https://thanhnien.vn/nguoi-phu-nu-viet-phat-trien-vat-lieu-phu-chong-chay-o-uc-post1401084.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9277)
                        },
                        new
                        {
                            NewsId = 18,
                            Content = "Người Việt xa xứ",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Những ký ức về người bà quá cố và các món ăn Việt mà bà chuẩn bị cho gia đình khi xưa đã dẫn dắt đầu bếp David Huynh.",
                            LanguageId = "vi",
                            Name = "Cảm hứng từ bữa ăn Việt của bà",
                            Source = "https://thanhnien.vn/cam-hung-tu-bua-an-viet-cua-ba-post1401081.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9279)
                        },
                        new
                        {
                            NewsId = 19,
                            Content = "Giao thông",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bốn đoàn tàu tuyến metro số 1 (tuyến Bến Thành - Suối Tiên) dự kiến từ Nhật Bản về TP.HCM cuối tháng 11 và đầu tháng 12.",
                            LanguageId = "vi",
                            Name = "Gặp bão, đoàn tàu metro trễ hẹn về TP.HCM",
                            Source = "https://thanhnien.vn/gap-bao-doan-tau-metro-tre-hen-ve-tp-hcm-post1406682.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9281)
                        },
                        new
                        {
                            NewsId = 20,
                            Content = "Xuất khẩu",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Số liệu công bố từ Tổng cục Thống kê cho thấy 11 tháng năm 2021, Việt Nam xuất khẩu đạt tổng trị giá 299,67 tỉ USD.",
                            LanguageId = "vi",
                            Name = "Xuất khẩu thép lần đầu cán mốc 10 tỉ USD",
                            Source = "https://thanhnien.vn/xuat-khau-thep-lan-dau-can-moc-10-ti-usd-post1406650.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9283)
                        },
                        new
                        {
                            NewsId = 21,
                            Content = "Giao thông",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "UBND TP.HCM vừa có văn bản khẩn gửi Bộ Kế hoạch - Đầu tư liên quan đến dự kiến phương án phân bổ vốn đầu tư công năm 2022 nguồn vốn ngân sách T.Ư.",
                            LanguageId = "vi",
                            Name = "TP.HCM khát vốn cho giao thông",
                            Source = "https://thanhnien.vn/tp-hcm-khat-von-cho-giao-thong-post1406453.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9285)
                        },
                        new
                        {
                            NewsId = 22,
                            Content = "Tài chính",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dự ước năm 2021, lượng kiều hối chuyển về VN sẽ đạt mức kỷ lục 18,1 tỉ USD, bất chấp dịch Covid-19.",
                            LanguageId = "vi",
                            Name = "Lượng kiều hối tăng mạnh kỷ lục",
                            Source = "https://thanhnien.vn/luong-kieu-hoi-tang-manh-ky-luc-post1405536.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9287)
                        },
                        new
                        {
                            NewsId = 23,
                            Content = "Chứng khoán",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tiền gửi tiết kiệm sụt giảm trong khi dòng vốn tham gia vào thị trường chứng khoán ngày càng tăng.",
                            LanguageId = "vi",
                            Name = "Dòng vốn mạnh đưa chứng khoán lập đỉnh",
                            Source = "https://thanhnien.vn/dong-von-manh-dua-chung-khoan-lap-dinh-post1404799.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9288)
                        },
                        new
                        {
                            NewsId = 24,
                            Content = "Học hành",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dạy học môn lịch sử trong trường phổ thông như thế nào để học sinh không chán là vấn đề luôn luôn mới.",
                            LanguageId = "vi",
                            Name = "Tin tức giáo dục đặc biệt 1.12: Dạy sử bằng nội dung cảm xúc hay sự kiện?",
                            Source = "https://thanhnien.vn/tin-tuc-giao-duc-dac-biet-1-12-day-su-bang-noi-dung-cam-xuc-hay-su-kien-post1406754.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9290)
                        },
                        new
                        {
                            NewsId = 25,
                            Content = "Đại học",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Những lưu ý gì cho thí sinh để vào được đúng ngành nghề yêu thích, phù hợp với điểm số, là vấn đề mà rất nhiều thí sinh hiện đang băn khoăn.",
                            LanguageId = "vi",
                            Name = "Hướng vào đại học phù hợp với điểm thi",
                            Source = "https://thanhnien.vn/huong-vao-dai-hoc-phu-hop-voi-diem-thi-post989845.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9292)
                        },
                        new
                        {
                            NewsId = 26,
                            Content = "Giáo viên",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Từ một chàng thợ xây thích chơi đùa cùng trẻ em, thầy giáo Nguyễn Hồ Tây Phương đã trở thành người thầy hiếm hoi dấn thân mình với nghề dạy dỗ trẻ mầm non.",
                            LanguageId = "vi",
                            Name = "Gặp người thầy… đẹp trai nhất trường mầm non!",
                            Source = "https://thanhnien.vn/gap-nguoi-thay-dep-trai-nhat-truong-mam-non-post1403127.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9293)
                        },
                        new
                        {
                            NewsId = 27,
                            Content = "Giáo viên",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thầy Nguyễn Viết Tước đã được các cấp từ trung ương đến địa phương khen thưởng hơn 7 triệu đồng.",
                            LanguageId = "vi",
                            Name = "Thầy giáo dùng tiền khen thưởng ủng hộ Quỹ phòng chống Covid-19",
                            Source = "https://thanhnien.vn/thay-giao-dung-tien-khen-thuong-ung-ho-quy-phong-chong-covid-19-post1075098.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9295)
                        },
                        new
                        {
                            NewsId = 28,
                            Content = "Đại học",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khoa Y ĐH Quốc gia TP.HCM thông báo xét tuyển bổ sung 3 ngành ĐH hệ chính quy, trong đó có ngành y khoa.",
                            LanguageId = "vi",
                            Name = "Khoa Y ĐH Quốc gia TP.HCM xét tuyển bổ sung cả thí sinh tự do",
                            Source = "https://thanhnien.vn/khoa-y-dh-quoc-gia-tp-hcm-xet-tuyen-bo-sung-ca-thi-sinh-tu-do-post1116655.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9297)
                        },
                        new
                        {
                            NewsId = 29,
                            Content = "Trò chơi",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bản nâng cấp mới sẽ khả dụng vào năm 2022 và hoàn toàn miễn phí cho chủ sở hữu các thiết bị PS4 và Xbox One.",
                            LanguageId = "vi",
                            Name = "Bản nâng cấp Cyberpunk 2077 sẽ miễn phí cho chủ sở hữu PS4 và Xbox One",
                            Source = "https://thanhnien.vn/ban-nang-cap-cyberpunk-2077-se-mien-phi-cho-chu-so-huu-ps4-va-xbox-one-post1406595.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9298)
                        },
                        new
                        {
                            NewsId = 30,
                            Content = "Trò chơi",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phi Vụ Triệu Đô bất ngờ quay trở lại Đảo Quân Sự Free Fire lần thứ hai với phần đặc biệt.",
                            LanguageId = "vi",
                            Name = "Phi Vụ Triệu Đô tái kết hợp Free Fire trong phần đặc biệt: Phi Vụ Cuối Cùng tháng 12 này",
                            Source = "https://thanhnien.vn/phi-vu-trieu-do-tai-ket-hop-free-fire-trong-phan-dac-biet-phi-vu-cuoi-cung-thang-12-nay-post1406503.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9300)
                        },
                        new
                        {
                            NewsId = 31,
                            Content = "Trò chơi",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giải đấu mang quy mô quốc tế đầu tiên của LMHT: Tốc Chiến vừa kết thúc tại Singapore và một đội tuyển của Việt Nam vào Top 5-6.",
                            LanguageId = "vi",
                            Name = "Việt Nam lọt Top 5 đội LMHT: Tốc Chiến thế giới",
                            Source = "https://thanhnien.vn/viet-nam-lot-top-5-doi-lmht-toc-chien-the-gioi-post1404103.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9491)
                        },
                        new
                        {
                            NewsId = 32,
                            Content = "Trò chơi",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tên của 4 thành phố dự kiến tổ chức giải Chung kết Thế giới 2022 bộ môn eSport Liên Minh Huyền Thoại vô tình bị lộ trong một video thông báo.",
                            LanguageId = "vi",
                            Name = "Riot Games để lộ 4 địa điểm của Chung kết LMHT Thế giới 2022",
                            Source = "https://thanhnien.vn/riot-games-de-lo-4-dia-diem-cua-chung-ket-lmht-the-gioi-2022-post1403726.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9496)
                        },
                        new
                        {
                            NewsId = 33,
                            Content = "Trò chơi",
                            DatePublished = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bộ phim hoạt hình mang tên Arcane về thế giới trong Liên Minh Huyền Thoại đang nhận đánh giá tốt.",
                            LanguageId = "vi",
                            Name = "Arcane giúp Vi và Jinx tăng vọt tỉ lệ được chọn trong LMHT",
                            Source = "https://thanhnien.vn/arcane-giup-vi-va-jinx-tang-vot-ti-le-duoc-chon-trong-lmht-post1401689.html",
                            Status = 0,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 202, DateTimeKind.Local).AddTicks(9498)
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.NewsInTopics", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 12, 1, 23, 23, 39, 162, DateTimeKind.Local).AddTicks(2458));

                    b.HasKey("TopicId", "NewsId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsInTopics");

                    b.HasData(
                        new
                        {
                            TopicId = 2,
                            NewsId = 3,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 2,
                            NewsId = 2,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 1,
                            NewsId = 1,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 5,
                            NewsId = 8,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 6,
                            NewsId = 8,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 8,
                            NewsId = 7,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 8,
                            NewsId = 9,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 9,
                            NewsId = 10,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 9,
                            NewsId = 11,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 9,
                            NewsId = 12,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 9,
                            NewsId = 13,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 9,
                            NewsId = 14,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 10,
                            NewsId = 15,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 10,
                            NewsId = 16,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 10,
                            NewsId = 17,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 10,
                            NewsId = 18,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 11,
                            NewsId = 19,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 11,
                            NewsId = 20,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 11,
                            NewsId = 21,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 11,
                            NewsId = 22,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 11,
                            NewsId = 23,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 24,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 25,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 26,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 27,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 28,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 12,
                            NewsId = 29,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 13,
                            NewsId = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 13,
                            NewsId = 31,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 13,
                            NewsId = 32,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TopicId = 13,
                            NewsId = 33,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3314be5-4c77-4fb6-82ad-302014682a73"),
                            ConcurrencyStamp = "570d3e06-927d-4baa-a68c-ca830fee9267",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13"),
                            ConcurrencyStamp = "b573c0f7-b1b1-41dc-b4d3-8f60eb50d077",
                            Name = "Subscriber",
                            NormalizedName = "Subscriber"
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SourceId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int?>("Thumbstory")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 12, 1, 23, 23, 39, 176, DateTimeKind.Local).AddTicks(2307));

                    b.HasKey("StoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Thumbstory")
                        .IsUnique()
                        .HasFilter("[Thumbstory] IS NOT NULL");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.TopicNews", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("normal");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ThumbTopic")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TopicId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ThumbTopic")
                        .IsUnique()
                        .HasFilter("[ThumbTopic] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("TopicNews");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            Description = "Follow live as the Taliban seizes territory across Afghanistan in the wake of the U.S. withdrawal.",
                            Label = "breaking",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "afghanistan",
                            ThumbTopic = 3,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9581)
                        },
                        new
                        {
                            TopicId = 2,
                            Description = "Best nonfiction features, in-depth stores and other long-form content from across the web.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "in-depth",
                            ThumbTopic = 2,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9937)
                        },
                        new
                        {
                            TopicId = 3,
                            Description = "Outbreak of respiratory virus that has killed over 1 million and infected 100 milion worldwide.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "coronavirus",
                            ThumbTopic = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9949)
                        },
                        new
                        {
                            TopicId = 4,
                            Description = "The top business and economic news from around the world with a focus on the United State.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "top-business",
                            ThumbTopic = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9951)
                        },
                        new
                        {
                            TopicId = 5,
                            Description = "Follow the presidential transition of Joe Biden, including policy plans, appointments and more.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "biden-admin",
                            ThumbTopic = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9953)
                        },
                        new
                        {
                            TopicId = 6,
                            Description = "Top stories from around the world with a focus on news not covered in other feeds.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "top-news",
                            ThumbTopic = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9955)
                        },
                        new
                        {
                            TopicId = 7,
                            Description = "Follow important local news: politics, business, top events and more. Updated everything evening.",
                            Label = "featured",
                            LanguageId = "en",
                            Status = 0,
                            Tag = "boston",
                            ThumbTopic = 1,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9956)
                        },
                        new
                        {
                            TopicId = 8,
                            Description = "Kinh tế Việt Nam trong năm.",
                            Label = "Thế giới",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "tin tức",
                            ThumbTopic = 3,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9957)
                        },
                        new
                        {
                            TopicId = 9,
                            Description = "Cuộc sống của người Việt Trên toàn thế giới.",
                            Label = "Thế giới",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "người Việt Nam",
                            ThumbTopic = 4,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9959)
                        },
                        new
                        {
                            TopicId = 10,
                            Description = " Nền doanh nghiệp Việt Nam.",
                            Label = "TÀI CHÍNH - KINH DOANH",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "Kinh tế",
                            ThumbTopic = 5,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9960)
                        },
                        new
                        {
                            TopicId = 11,
                            Description = "Chọn trường nghề phù hợp với bản thân.",
                            Label = "GIÁO DỤC",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "học hành",
                            ThumbTopic = 6,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9962)
                        },
                        new
                        {
                            TopicId = 12,
                            Description = "Công nghệ mới trong game.",
                            Label = "Trò chơi",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "Trò chơi",
                            ThumbTopic = 7,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9964)
                        },
                        new
                        {
                            TopicId = 13,
                            Description = " Sản phẩm công nghệ mới trong năm.",
                            Label = "Công Nghệ",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "Sản phẩm",
                            ThumbTopic = 8,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9965)
                        },
                        new
                        {
                            TopicId = 14,
                            Description = " Phóng sự đời sống thường nhật của người dân.",
                            Label = "Thời sự",
                            LanguageId = "vi",
                            Status = 0,
                            Tag = "Phóng sự",
                            ThumbTopic = 9,
                            Timestamp = new DateTime(2021, 12, 1, 23, 23, 39, 201, DateTimeKind.Local).AddTicks(9967)
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId")
                        .IsUnique()
                        .HasFilter("[AvatarId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69db714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "744b486a-c1e6-411e-9119-a0493ed7ef5b",
                            Email = "bp.khuyen@hutech.edu.vn",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bui Phu Khuyen",
                            NormalizedEmail = "BP.KHUYEN@HUTECH.EDU.VN",
                            NormalizedUserName = "khuyenpb",
                            PasswordHash = "AQAAAAEAACcQAAAAEHG5ZRaK5lu1VbBDZ4MbfVcwJRpON0gApa7zeWsZ/AX3D0/YxeouAaSCEIPoXqrCNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "khuyenpb"
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69db714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("a3314be5-4c77-4fb6-82ad-302014682a73")
                        });
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Vote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 12, 1, 23, 23, 39, 173, DateTimeKind.Local).AddTicks(5665));

                    b.Property<bool>("isReal")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "NewsId");

                    b.HasIndex("NewsId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey", "UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Follow", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.TopicNews", "TopicNews")
                        .WithMany("Follows")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicNews");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.News", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Language", "Language")
                        .WithMany("News")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.Media", "Media")
                        .WithOne("News")
                        .HasForeignKey("FakeNewsFilter.Data.Entities.News", "ThumbNews");

                    b.Navigation("Language");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.NewsInTopics", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.News", "News")
                        .WithMany("NewsInTopics")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.TopicNews", "TopicNews")
                        .WithMany("NewsInTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("TopicNews");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Source", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Language", "Language")
                        .WithMany("Source")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Story", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Language", "Language")
                        .WithMany("Story")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.Source", "Source")
                        .WithMany("Story")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.Media", "Media")
                        .WithOne("Story")
                        .HasForeignKey("FakeNewsFilter.Data.Entities.Story", "Thumbstory");

                    b.Navigation("Language");

                    b.Navigation("Media");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.TopicNews", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Language", "Language")
                        .WithMany("TopicNews")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.Media", "Media")
                        .WithOne("TopicNews")
                        .HasForeignKey("FakeNewsFilter.Data.Entities.TopicNews", "ThumbTopic");

                    b.HasOne("FakeNewsFilter.Data.Entities.User", null)
                        .WithMany("TopicId")
                        .HasForeignKey("UserId");

                    b.Navigation("Language");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.User", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Media", "Avatar")
                        .WithOne("User")
                        .HasForeignKey("FakeNewsFilter.Data.Entities.User", "AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.UserRoles", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Vote", b =>
                {
                    b.HasOne("FakeNewsFilter.Data.Entities.News", "News")
                        .WithMany("Vote")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeNewsFilter.Data.Entities.User", "User")
                        .WithMany("Vote")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Language", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Source");

                    b.Navigation("Story");

                    b.Navigation("TopicNews");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Media", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Story");

                    b.Navigation("TopicNews");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.News", b =>
                {
                    b.Navigation("NewsInTopics");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.Source", b =>
                {
                    b.Navigation("Story");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.TopicNews", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("NewsInTopics");
                });

            modelBuilder.Entity("FakeNewsFilter.Data.Entities.User", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("TopicId");

                    b.Navigation("UserRoles");

                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
